plugins:
  - jsdoc
root: true
extends:
  - airbnb-base
globals:
  Tagify: readonly
  bootstrap: readonly
parserOptions:
  sourceType: "module"
  ecmaVersion: 2020
env:
  browser: true
  es6: true
rules:
  "import/extensions": [2, {
    "js": "always"
  }]
  indent: ["off"]
  no-restricted-syntax: ["error", "LabeledStatement", "WithStatement"]
  class-methods-use-this: "off"
  no-underscore-dangle: "off"
  require-jsdoc: ["warn"]
  no-await-in-loop: ["off"]
  object-curly-newline: ["off"]
  no-plusplus: ["off"]
  prefer-destructuring:
    - error
    - array: false
      object: true
    - enforceForRenamedProperties: false
