apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony-work-reaper
  labels:
    name: harmony-work-reaper
spec:
  replicas: $WORK_REAPER_POD_REPLICAS
  selector:
    matchLabels:
      name: harmony-work-reaper
  template:
    metadata:
      labels:
        name: harmony-work-reaper
    spec:
      containers:
        - name: harmony-work-reaper
          imagePullPolicy: IfNotPresent
          image: $WORK_REAPER_IMAGE
          resources:
            limits:
              memory: $WORK_REAPER_LIMITS_MEMORY
              cpu: $WORK_REAPER_LIMITS_CPU
            requests:
              memory: $WORK_REAPER_REQUESTS_MEMORY
              cpu: $WORK_REAPER_REQUESTS_CPU
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: REAPABLE_WORK_AGE_MINUTES
            value: '$REAPABLE_WORK_AGE_MINUTES'
          - name: WORK_REAPER_BATCH_SIZE
            value: '$WORK_REAPER_BATCH_SIZE'
          - name: WORK_REAPER_PERIOD_SEC
            value: '$WORK_REAPER_PERIOD_SEC'
          ports:
            - containerPort: $PORT
---
apiVersion: v1
kind: Service
metadata:
  name: harmony-work-reaper
spec:
  ports:
    - name: frontend
      port: $PORT
      targetPort: $PORT
      protocol: TCP
  selector:
    name: harmony-work-reaper
  type: ClusterIP