kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
      - '/etc/alertmanager/*.tmpl'
    route:
      receiver: default
      group_by: [alertname]
      group_wait: 5m
      group_interval: 10m
      repeat_interval: 2h
      routes:
    receivers:
      - name: 'default'
        sns_configs:
        - topic_arn: $ALERT_MANAGER_TOPIC_ARN
          subject: '[Alert Manager $CLIENT_ID] {{ .GroupLabels.alertname }}'
          sigv4:
            region: $AWS_DEFAULT_REGION
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    template
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.23.0
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              memory: $ALERT_MANAGER_REQUESTS_MEMORY
              cpu: $ALERT_MANAGER_REQUESTS_CPU
            limits:
              memory: $ALERT_MANAGER_LIMITS_MEMORY
              cpu: $ALERT_MANAGER_LIMITS_CPU
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: templates-volume
          mountPath: /etc/alertmanager-templates
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: templates-volume
        configMap:
          name: alertmanager-templates
      - name: alertmanager
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093